name: Release Package

permissions:
  repository-projects: write

on:
  release:
    types: [created]

env:
  NPM_TOKEN: ""

jobs:
  build-and-publish:
    permissions:
      packages: write
      contents: write
      pull-requests: write
      issues: write
      repository-projects: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: ./scripts/publish.sh
