name: Build Test

on:
  push:
    branches: ["master"]

env:
  NPM_TOKEN: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Installing dependencies
        run: ./.yarn/releases/yarn-3.3.1.cjs
      - name: Validating TypeScript
        run: ./.yarn/releases/yarn-3.3.1.cjs test:tsc
      - name: Validating ESLint
        run: ./.yarn/releases/yarn-3.3.1.cjs test:lint
      - name: Validating Prettier
        run: ./.yarn/releases/yarn-3.3.1.cjs test:prettier
      - name: Running Unit Tests
        run: ./.yarn/releases/yarn-3.3.1.cjs test:jest
