name: Build Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  NPM_TOKEN: ""

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Installing dependencies
        run: ./.yarn/releases/yarn-1.22.19.cjs --frozen-lockfile
      - name: Validating TypeScript
        run: ./.yarn/releases/yarn-1.22.19.cjs test:tsc
      - name: Validating ESLint
        run: ./.yarn/releases/yarn-1.22.19.cjs test:lint
      - name: Validating Prettier
        run: ./.yarn/releases/yarn-1.22.19.cjs test:prettier
      - name: Building package
        run: ./.yarn/releases/yarn-1.22.19.cjs build
      - name: Running Unit Tests
        run: ./.yarn/releases/yarn-1.22.19.cjs test:jest
